### ISSUE TITLE
第21课时代码没有上传喔，麻烦老师上传下！ 

### ISSUE THREAD

**Issue by willokyes** [love-flutter/flutter-column#2]

**Comment by love-flutter** [comment]
ok，国庆节补一下

**Comment by love-flutter** [comment]
@willokyes 这两天上传哈，抱歉，最近换了公司，代码没有保留。我这两天会把21课时代码再重新写下。悲剧的事情

**Comment by love-flutter** [comment]
已经上传，其次解决了部分在flutter 1.22.1 兼容性问题。还有增加 mock 接口的超时时间，避免接口失败异常
